TARGET = SOM

SOM:
	gcc ../../ADT/point/point.c ../../ADT/linkedlist/listdp.c ../../ADT/mesinkata/mesinkata.c ../../ADT/mesinkarakter/mesinkarakter.c SoM.c mainSoM.c -o $(TARGET)

clean:
	rm $(TARGET)