TARGET = Hangman

Hangman:
	gcc ../../ADT/mesinkata/mesinkata.c ../../ADT/mesinkarakter/mesinkarakter.c ../../ADT/queue/queue.c ../../ADT/map/map.c Hangman.c mainH.c -o $(TARGET)

clean:
	rm $(TARGET)